[package]
name = "ImamU - CCIS Report template"
description = "A Typst template to quickly scaffold a report for your projects and Assignments at ImamU"
version = "0.2.0"
entrypoint = "lib.typ"
license = "MIT"
authors = ["Abdulaziz Bin Askar"]
categories = ["report"]
keywords = ["ImamU","IMSIU", "report", "academic", "project"]
exclude = ["example.pdf"]
repository = "https://github.com/AFAskar/Imamu-CCIS-Report-Template"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "template/thumbnail.png"
